[tool.poetry]
name = "csv_bleach"
version = "0.2.3"
description = "clean CSVs"
authors = ["George Burton <g.e.c.burton@gmail.com>"]
readme = "README.md"
license = "MIT"
keywords = ["csv"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Text Processing"
]
repository = "https://github.com/gecBurton/csv-bleach"

[tool.poetry.dependencies]
python = ">=3.8.1"
click = "^8.1.3"
chardet = "^5.1.0"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
pytest = "^7.1.3"
mypy = "^0.991"
isort = "^5.10.1"
types-chardet = "^5.0.4"
flake8 = "^6.0.0"
pytest-cov = "^4.0.0"
Flake8-pyproject = "^1.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bleach = 'bleach.__main__:cli'

[project.scripts]
bleach = 'bleach.__main__:cli'

[tool.flake8]
ignore = ['E501', 'W503']
max-line-length = 88
